### ISSUE TITLE
is there any way I can access the containers on the host which the contaienrs are running?

### ISSUE THREAD

**Issue by andyliuliming** [cloudfoundry/guardian#117]
## Todos

Please try the following before submitting the issue:

- [x] Upgrade Concourse if you are observing a failure in a test
- [x] Use latest BOSH stemcell if the problem occurred in a BOSH VM
- [x] Use Go 1.6 if the issue has to do with running unit tests locally

## Description

I'm trying to access the apps on the diego-cell which the app containers running.
say I'm trying to access 
10.0.16.5:61000, 10.0.16.5 is the diego-cell eth0's ip.

but from other node in the same subnet, say, a vm with ip 10.0.16.4.
i can wget 10.0.16.5:61000.
seems the ip:port could not been accessed only in the containers are running on.

could you please help?

## Logging and/or test output

Provide any output you think may help understanding further the issue. Guardian
stores its log files in `/var/vcap/sys/log/garden` when run through its BOSH
release.

## Steps to reproduce

Outline the steps to test or reproduce the PR here. Please also provide the
following information if applicable:

* Guardian release version
* Linux kernel version
* Concourse version
* Go version

**Comment by andyliuliming** [comment]
in the host:

sudo tcptraceroute 10.0.16.5 61000 -n
traceroute to 10.0.16.5 (10.0.16.5), 30 hops max, 60 byte packets
 1  10.0.16.5 <rst,ack>  0.039 ms  0.012 ms  0.010 ms

in the other node:
sudo tcptraceroute 10.0.16.5 61000 -n
traceroute to 10.0.16.5 (10.0.16.5), 30 hops max, 60 byte packets
 1  10.0.16.5  1.110 ms  0.633 ms  1.085 ms
 2  10.0.16.5 <syn,ack>  1.248 ms  1.347 ms  1.291 ms

**Comment by julz** [comment]
Hi @andyliuliming - this is expected behaviour for security reasons. If you want to enable networking between containers in cf I'd suggest enabling https://github.com/cloudfoundry/cf-networking-release, which I believe is the default in recent versions of `cf-deployment`. This should allow you to explicitly allow container-to-container access between different apps using `cf add-network-policy`.

**Comment by andyliuliming** [comment]
@julz thanks for the response.
I'm not saying the container-to-container access.
I mean I want to access the app in the "host" which the containers are running.
the "10.0.16.5" is the host ip.
and the "10.255.74.3" is the ip of the container.

the registered address is "10.0.16.5:61000", the address can be accessed in any nodes(the diego cell node, cc node, or any other nodes in the same subnet).
but we could not access this address in the host which this container are running on.

**Comment by andyliuliming** [comment]
if the container-to-container rule can make this happen. could you please tell me what's the exact parameter to do this?
thanks.

**Comment by andyliuliming** [comment]
@julz or is there anything I can modify to make apps accessible from the diego-cell host?
thanks.

**Comment by julz** [comment]
I see, this is controlled by the [`allow-host-access` flag](https://github.com/cloudfoundry/garden-runc-release/blob/develop/jobs/garden/spec#L51), but this is set to false for a good reason: allowing containers to access the host might expose a security vulnerability if applications on the host assume untrusted users will not be able to access local network addresses, which many do. I'd strongly advise against changing the value of this flag in production environments.

Maybe you could explain a bit more about your use case for having containers access applications in the host VM? Could you run the service you want to provide to the apps in a container or on a different host?

**Comment by andyliuliming** [comment]
@julz I suppose the allow-host-access will not help : )
maybe I did not tell the story clearly.

the 10.0.16.5 is the host ip.
the gardian would map 10.0.16.5:61000 to 10.255.202.6:8080

what I'm trying to do is to access the 10.0.16.5:61000 at the diego-cell host:

**diego-cell/c1b52ca3-9366-46d4-8cfe-b6bd434aec38:/var/vcap/bosh_ssh/bosh_9fdf833c1516401# wget 10.0.16.5:61000
--2018-07-01 13:43:26--  http://10.0.16.5:61000/
Connecting to 10.0.16.5:61000... failed: Connection refused.**


why I do this is I'm trying to deploy the go-router and the diego-cell at the same node.
but when go-router trying to access the 10.0.16.5:61000, it got the connection refused.

**Comment by andyliuliming** [comment]
ah, seems 
iptables -t nat -A OUTPUT -p tcp -d 10.0.16.5 --dport 61000 -j DNAT --to-destination 10.255.202.6:8080 can help us reach this goal.
