### ISSUE TITLE
Guardian fails to StreamIn when given SteamInSpec.Path = "/"

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/guardian#122]
## Todos

Please try the following before submitting the issue:

- [x] Upgrade Concourse if you are observing a failure in a test
**Not seeing this in Concourse. Seeing it when executing a CLI by hand from our local workstation.**
- [x] Use latest BOSH stemcell if the problem occurred in a BOSH VM
**We are running Garden inside BOSH lite. It is running the latest version.**
- [x] Use Go 1.6 if the issue has to do with running unit tests locally
**Not an issue with tests.**

## Description
We are using Garden as a container runtime for executing [Cloud Native Application Bundles](https://cnab.io/). Part of the specification for these bundles is that parameters may be passed to the invocation container as files. The location of the files is specified by the bundle author and may include files at the root path, like `/somefile.json`.

We made an attempt to use the Garden `container.StreamIn` API to copy these parameter files into the container. Unfortunately, when we provide a path of `/` with our tarstream, we get the following error:
```
mkdir_p_as 0 0: No such file or directory
```

Our best guess is that this is caused by this section of code in `nstar`: https://github.com/cloudfoundry/guardian/blob/master/rundmc/nstar/nstar.c#L58-L59.

## Steps to reproduce

Outline the steps to test or reproduce the PR here. Please also provide the
following information if applicable:

* Garden RunC Release Version: 1.18.3
* BOSH Warden Stemcell: Xenial v250.17
* Concourse version: NA
* Go version: 1.11.4

Use the Garden client API `container.StreamIn` feature, passing any simple tar as `TarStream`, and `/` as `Path`. You will see the error shown above returned to the client and printed in the server logs.

/cc @youreddy

**Comment by Callisto13** [comment]
This fix will be available from GRR v1.19.1. I will close when we release.
