### ISSUE TITLE
wbrdg interfaces being removed from nodes

### ISSUE THREAD

**Issue by geofffranks** [cloudfoundry/guardian#68]
## Todos

Please try the following before submitting the issue:

- [ ] Upgrade Concourse if you are observing a failure in a test
- [ ] Use latest BOSH stemcell if the problem occurred in a BOSH VM
- [ ] Use Go 1.6 if the issue has to do with running unit tests locally

## Description

Something appears to be removing arbitrary `wbrdg-` devices associated with containers being created via diego + garden-runc. Some time after pushing an app, and it being accessible, it becomes inaccessible with 502 gateway timeouts. The container is still running and healthy, but it has no network access. Digging deeper shows that the `wbrdg-` device associated with the container is no longer present on the host VM.

## Logging and/or test output

dmesg output:

```[1106618.537836] IPv6: ADDRCONF(NETDEV_CHANGE): wbrdg-0afe0040: link becomes ready
[1106633.564037] wbrdg-0afe0040: port 1(w9d6409ch3e1-0) entered forwarding state
[1106759.581682] device w9d6409ch3e1-0 left promiscuous mode
[1106759.581711] wbrdg-0afe0040: port 1(w9d6409ch3e1-0) entered disabled state```

https://gist.github.com/geofffranks/9e621a9c559d2d49dfcf7c41bb8f76ad has veritas + ip addr output on the cell node

based on the ip addr output in the gist, t looks like something removed the wbrdg-0afe00f0 interface from the cell node.

## Steps to reproduce

This is occurring on a BOSH-Lite VM running in Azure (rather than virtualbox)
cf-249
diego 1.2.0
garden 1.0.4
BOSH director version is 1.3262.9.0 (257.9)
warden-cpi version 29
bosh-warden-ubuntu stemcell v3312.17 (i'm in the process of trying this on v3363.1)

Essentially the steps to reproduce are to push a few apps, wait a period of time, and wait for one of them to become unresponsive. It's possible that this happened in conjunction with stopping/deleting other apps, as i most recently noticed this after having deleted a bunch of apps related to cf acceptance tests.

**Comment by geofffranks** [comment]
Updated to latest warden stemcell, and the issue occurred overnight. Per @julz's request, upgrading the bosh-lite to use garden-runc vs garden-linux, to see if that helps the inside garden-runc environment for diego.

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#140553063](https://www.pivotaltracker.com/story/show/140553063) wbrdg interfaces being removed from nodes


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by geofffranks** [comment]
Tested this using garden-runc for the bosh-lite finally (this time on vSphere), and the problem did not occur within 36 hours. Moved back to garden-linux on the bosh-lite and within 12 hours the problem had occurred on all of 5 of my apps.

I would move to garden-runc at the bosh-lite level, but will need https://github.com/cppforlife/bosh-warden-cpi-release/issues/5 resolved first

**Comment by julz** [comment]
Great work @geofffranks thanks for all the work debugging in to this! Sounds like we basically have a solution (move bosh-lite to garden-runc) pending resolution of https://github.com/cppforlife/bosh-warden-cpi-release/issues/5 so I'll close this one and we'll focus on that. Thanks again!
